import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";

const fira_code = Fira_Code({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={fira_code.className + " overflow-hidden"}>
        <main className="max-w-7xl m-auto grid grid-cols-3 gap-4">
          <div className="h-screen flex flex-col pt-16">
            <div>
              <h2 className="text-6xl font-medium">
                Hi, <br /> I`m Ostap
              </h2>
              <h4 className="text-xl mt-9">
                Front-End Developer from Porto :)
              </h4>
              <span className="text-lg mt-9 inline-block">
                Welcome to my personal site You can check my Portfolio with the
                link below
              </span>
            </div>

            <div className="mt-auto">dots HErE</div>
          </div>
          <div className="col-span-2">{children}</div>
        </main>
      </body>
    </html>
  );
}
